### ISSUE TITLE
Correct rendering when resizing

### ISSUE THREAD

**Issue by Elime1** [orange451/LWJGUI#18]
Rendering on resize does not behave as I expected.

```
    private void loop() {
        while (!glfwWindowShouldClose(window) ) {
            render();
            glfwPollEvents();
        }
    }
```

```
    glfwSetWindowSizeCallback(window, (handle, width, height) -> render());
```

```
    private void render() {
        WindowManager.update();
        glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
        lwjguiWindow.render();
        glfwSwapBuffers(window);
    }
```

![resize-test](https://user-images.githubusercontent.com/9988754/86491913-87c25900-bd6c-11ea-91ae-cfa0f6a438cc.gif)

**Comment by Guerra24** [comment]
Not the correct usage, once a window is wrapped with LWJGUI you cannot use `glfwSet*Callback` calls, doing so will remove the custom callbacks used by the window. The correct way is to add your callback using `window.getWindowSizeCallback`.

Also should never call `WindowManager.update` from withing a callback due to GLFW limitations.

**Comment by Elime1** [comment]
I see. It's woking great now. Thank you very much!
